### ISSUE TITLE
Void Spawn error

### ISSUE THREAD

**Issue by PotatoTheSimp** [endercrest/VoidSpawn#98] opened 2021-12-27 02:12 UTC
**Describe the bug**
After setting up the plugin correctly with the ingame commands **AND** the config file i keep on getting this error i've tried everything to solve it this is on a bungeecord server running purpur 1.18.1 it szeems to be say that world is invalid but i am in the world right now and i set it while being in it its weird

**To Reproduce**
1. configure the plugin
2.jump into void

**Expected behavior**
teleporting to spawn

**Screenshots**
![2021-12-27_03 06 38](https://user-images.githubusercontent.com/96707811/147427371-1baf33f2-c779-4acc-a826-ff6d252b1abe.png)
![here](https://user-images.githubusercontent.com/96707811/147427397-09317236-b4ec-4f5e-8882-b82205509659.PNG)
![cons](https://user-images.githubusercontent.com/96707811/147427455-2b65369f-6fa2-4f82-b6c7-37a8da26d102.PNG)

**VoidSpawn Version:**1.20.0
**MC Version:** MC: 1.18.1 purpur: (8183257) 
**Spigot Version:** not sure how to check this

**Comment by LukeAtomic** [comment] 2022-01-01 11:59
I would try change the config to this.

version: 2
spawn:
  spawn:
    x: -25.5
    y: 8.0
    z: -195.5
    pitch: -5.2253246
    yaw: -0.88910514
    world: Minigames World
  mode: command
  options:
    command: op:sudo ${player.name} spawn

I don't recommend having spaces in your world names.

**Comment by endercrest** [comment] 2024-09-30 23:16
Hey! Sorry you were having some problems with the plugin. This is likely caused by the space in the world name. Try changing your config to the following:

```yaml
version: 2
Minigames_World:
  spawn:
    x: -25.5
    y: 8.0
    z: -195.5
    pitch: -5.2253246
    yaw: -0.88910514
    world: Minigames_World
```

Going to close this off, but feel free to re-open this ticket if this is still a problem.

**Closed by endercrest** 2024-09-30 23:16 UTC
